### ISSUE TITLE
Investigate serialize exception

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#105]
<pre>
INFO   | jvm 1    | 2013/08/24 23:48:20 | 2013-08-24 23:48:20.327:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2013/08/24 23:48:20 | com.google.gwt.user.client.rpc.SerializationException: Type 'org.traccar.web.shared.model.ApplicationSettings' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer.For security purposes, this type will not be serialized.: instance = org.traccar.web.shared.model.ApplicationSettings@f6fd54
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:667)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:126)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:153)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:587)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:605)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.RPC.encodeResponseForSuccess(RPC.java:471)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:563)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2013/08/24 23:48:20 | 	at java.lang.Thread.run(Thread.java:679)
</pre>

**Comment by tananaev** [comment]
Old web interface is obsolete. This issue is no longer applicable.
