### ISSUE TITLE
Error when adding geofence : Remote procedure call error

### ISSUE THREAD

**Issue by hatami98** [tananaev/traccar-web#414]
Hi tananaev,

I got error when adding a new geofence. Below is what I have in wrapper log.
Thanks.

```
FINEST|1748/0|Service traccar|17-02-23 03:18:17|[qtp1200470358-38] WARN / - Exception while dispatching incoming RPC call
FINEST|1748/0|Service traccar|17-02-23 03:18:17|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.GeoFence org.traccar.web.client.model.DataService.addGeoFence(org.traccar.web.shared.model.GeoFence) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
NFO|1986/0|Service traccar|17-02-23 02:52:35|	at org.traccar.web.server.model.DataServiceImpl.getGeoFences(DataServiceImpl.java:969)
INFO|1986/0|Service traccar|17-02-23 02:52:37|	at org.traccar.web.server.model.DataServiceImpl.getGeoFences(DataServiceImpl.java:963)
FINEST|1748/0|Service traccar|17-02-23 03:08:53|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.GeoFence org.traccar.web.client.model.DataService.addGeoFence(org.traccar.web.shared.model.GeoFence) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
FINEST|1748/0|Service traccar|17-02-23 03:08:53|	at org.traccar.web.server.model.DataServiceImpl.addGeoFence(DataServiceImpl.java:996)
FINEST|1748/0|Service traccar|17-02-23 03:09:16|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.GeoFence org.traccar.web.client.model.DataService.addGeoFence(org.traccar.web.shared.model.GeoFence) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
FINEST|1748/0|Service traccar|17-02-23 03:09:16|	at org.traccar.web.server.model.DataServiceImpl.addGeoFence(DataServiceImpl.java:996)
FINEST|1748/0|Service traccar|17-02-23 03:16:31|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.GeoFence org.traccar.web.client.model.DataService.addGeoFence(org.traccar.web.shared.model.GeoFence) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
FINEST|1748/0|Service traccar|17-02-23 03:16:31|	at org.traccar.web.server.model.DataServiceImpl.addGeoFence(DataServiceImpl.java:996)
FINEST|1748/0|Service traccar|17-02-23 03:18:17|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.GeoFence org.traccar.web.client.model.DataService.addGeoFence(org.traccar.web.shared.model.GeoFence) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
FINEST|1748/0|Service traccar|17-02-23 03:18:17|	at org.traccar.web.server.model.DataServiceImpl.addGeoFence(DataServiceImpl.java:996)
FINEST|1748/0|Service traccar|17-02-23 03:18:46|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.GeoFence org.traccar.web.client.model.DataService.addGeoFence(org.traccar.web.shared.model.GeoFence) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
FINEST|1748/0|Service traccar|17-02-23 03:18:46|	at org.traccar.web.server.model.DataServiceImpl.addGeoFence(DataServiceImpl.java:996)
```

**Comment by tananaev** [comment]
This is a wrong project. Traccar doesn't use GWT since version 2.x.
